version: "3.9"

services:
  calculator:
    build: .
    depends_on:
      - graphdb
    volumes:
      - ./src:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network
    
  
  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      test-db: 
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./tests:/app/tests

  graphdb:
    image: neo4j:5
    ports:
      - "7474:7474"  # Web UI
      - "7687:7687"  # Bolt (для драйверов)
    environment:
      - NEO4J_AUTH=neo4j/testpassword
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data    
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 5s
    networks:
      - app-network

  test-db:
    image: postgres:15
    restart: always
    env_file: tests/.env
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 5s
    networks:
      - app-network
      

volumes:
  neo4j_data:
  neo4j_logs:
  pgdata:

networks:
  app-network:
    driver: bridge